
describe('Home Page', function()
{
    it('Visits the Home page', function()
    {
        const time_ms = 500
        const url = Cypress.config().baseUrl
        cy.log("Visiting the BC Services Card [DEV] URL")
        cy.visit(url)
        cy.wait(time_ms)
        cy.contains('Beta')
        cy.wait(time_ms)
        cy.log("Should contain a Button called LOGIN")
        cy.contains('Login')
        cy.wait(time_ms)
        cy.log("Should contain a Button called Learn More")
        cy.contains('Learn more')
        cy.wait(time_ms)
        cy.log("Should contain a Button called Get Started")
        cy.contains('Get started')
        cy.wait(time_ms)
        //If Clicked on Login
        cy.log("Click on Login button")
        cy.get('.d-none > .v-btn__content').click()
        cy.wait(time_ms)
        cy.log("Should Take user to Login Page")
        cy.url().should('include','/auth/realms')
        cy.wait(time_ms)
        cy.log("Back button should take back to home page")
        cy.go('back')
        cy.wait(time_ms)
        cy.url().should('eq',url+'/')
        cy.wait(time_ms)
        //If Clicked on Get Started
        cy.log("Click on Getting Started")
        cy.get('.getting-start-btn > .v-btn__content').click()
        cy.wait(time_ms)
        cy.url().should('include','-dev.pathfinder.gov.bc.ca/')
        cy.wait(time_ms)
        cy.log("Back button should take back to home page")
        cy.go('back')
        cy.wait(time_ms)
        cy.url().should('eq',url+'/')
        cy.wait(time_ms)
        //If clicked on Learn More
        cy.log("Clicking on Learn more should take user to Help page")
        cy.contains('Learn more').click()
        cy.wait(time_ms)
        cy.url().should('eq',url+'/help')
        cy.wait(time_ms)
        cy.log("Clicking on back button should take user to home page")
        cy.go('back')
        cy.url().should('eq',url+'/')
        cy.wait(time_ms)
        cy.scrollTo('bottom')
        //If clicked on Disclaimer, It opens in a separate window and does not allow to click back
        cy.log("Click on Disclaimer opens a URL in separate window")
        cy.contains('Disclaimer').click()
        
        cy.log("Check if window is open")
        cy.window().its('open')
        cy.wait(time_ms)
        cy.log("Back to Home Page")
        cy.visit(url)
        cy.scrollTo('bottom')
        //If clicked on Privacy, It opens in a separate window and does not allow to click back
        cy.log("Click on Privacy opens a URL in separate window")
        cy.contains('Privacy').click()
        
        cy.log("Check if window is open")
        cy.window().its('open')
        cy.wait(time_ms)
        cy.log("Back to Home Page")
        cy.visit(url)
        cy.scrollTo('bottom')
        //If clicked on Accessibility, It opens in a separate window and does not allow to click back
        cy.log("Click on Accessibility opens a URL in separate window")
        cy.contains('Accessibility').click()
        
        cy.log("Check if window is open")
        cy.wait(time_ms)
        cy.log("Back to Home Page")
        cy.visit(url)
        cy.scrollTo('bottom')
        //If clicked on Copyright, It opens in a separate window and does not allow to click back
        cy.log("Click on Copyright opens a URL in separate window")
        cy.contains('Copyright').click()
        
        cy.log("Check if window is open")
        cy.wait(time_ms)
        cy.log("Back to Home Page")
        cy.visit(url)
        cy.scrollTo('bottom')
        //If clicked on Terms of Use, It opens in a separate window and does not allow to click back
        cy.log("Click on Terms of Use opens a URL in separate window")
        cy.get('[href="/terms-of-use"]').click()
        cy.wait(time_ms)
        cy.log("Should take user to Terms of Use Page")
        cy.url().should('eq',url+'/terms-of-use')
        cy.wait(time_ms)
        cy.log("Back to Home Page")
        cy.go('back')   
        cy.url().should('eq',url+'/')
        cy.scrollTo('bottom')
        //If clicked on Contact US, It should allow to click back
        cy.log("Click on Contact Us opens a URL in the same window")
        cy.get('footer [href="/contact-us"]').click()    
        cy.wait(time_ms)
        cy.log("Should take user to Contact Us Page")
        cy.url().should('eq',url+'/contact-us')
        cy.wait(time_ms)
        cy.log("Clicking on back button should take user Back to Home Page")
        cy.go('back')   
        cy.url().should('eq',url+'/')
        cy.log("Test Complete")
    })
    
})