// Visit a web page
describe('Login with BC Services card in Demo Server ', function()
{
    const time_ms = 500
    it('Should have Prod Request disabled', function(){
        cy.log("Visiting the BC Services Card [DEMO] URL")
        cy.visit('https://selfservice-demo.pathfinder.gov.bc.ca/')
        cy.wait(time_ms)
        cy.log("Click to Login")
        cy.contains('Login').click()
        cy.wait(time_ms)
        //For the New url
        cy.log("Should open the login page")
        cy.url().should('include','openid-connect')
        cy.log("Click on BC Services Card Login")
        //Opting for BCSC login
        cy.get('#zocial-bcsc').click()
        cy.wait(time_ms)
        cy.log("Should open the BC Services Card Login Page")
        cy.url().should('eq','https://idtest.gov.bc.ca/login/entry#start')
        cy.wait(time_ms)
        cy.log("Click on Virtual Card Testing")
        //Click on Virtual Card Testing
        cy.get('#tile_btn_virtual_device_div_id > h2').click()
        cy.wait(time_ms)
        cy.log("Opens up the page with BC Services Card Login details")
        cy.contains('Virtual Card Testing')        
        cy.wait(time_ms)
        //Type the Card serial number and passcode
        cy.get('#csn').type('<Card serial number>').should('have.value', '<Card serial number>')
        cy.wait(time_ms)
        cy.log("Click on Continue to go to next page")
        cy.get('#continue').click()
        cy.wait(time_ms)
        cy.log("Enter Passcode")
        cy.get('#passcode').type('<Passcode>',{ log: false })
        cy.wait(time_ms)
        cy.log("Click Submit")
        cy.get('#btnSubmit').click()
        cy.wait(time_ms)
        cy.log("It should take user to validate page")
        cy.url().should('eq','https://idtest.gov.bc.ca/login/passcode/validate')
        cy.wait(time_ms)
        cy.log("Shows a disclaimer")
        cy.contains('BC Services Card Self Services for BPS - DEV will receive the following personal identity information')
        cy.wait(time_ms)
        cy.log("Click Submit")
        cy.get('#btnSubmit').click()
        cy.wait(time_ms)
        cy.url().should('include','https://selfservice-demo.pathfinder.gov.bc.ca/dashboard')
        cy.wait(time_ms)
        cy.get('tbody> tr > td >').click()
        cy.url().should('include','project-container')
        cy.log("The below assertion should NOT fail for Demo environment")
        cy.scrollTo('top')
        cy.get('[data-test-id="btn-request-prod-access"]').should('be.disabled')
        cy.wait(time_ms)
        cy.log("Test Completed")
    })
})