// Visit a web page
import "cypress-keycloak-commands";
describe('BC Keycloak Login with BC services Card', function()
{
    it('Visit the BC Dev Page and Login', function(){
        cy.log("Visiting the BC Services Card [DEV] URL")
        cy.visit('https://selfservice-dev.pathfinder.gov.bc.ca/')
        cy.wait(500)
        cy.log("Click to Login")
        cy.contains('Login').click()
        cy.wait(500)
        //For the New url
        cy.log("Should open the login page")
        cy.url().should('include','openid-connect')
        cy.log("Click on BC Services Card Login")
        //Opting for BCSC login
        cy.get('#zocial-bcsc').click()
        cy.wait(500)
        cy.log("Should open the BC Services Card Login Page")
        cy.url().should('eq','https://idtest.gov.bc.ca/login/entry#start')
        cy.wait(500)
        cy.log("Click on Virtual Card Testing")
        //Click on Virtual Card Testing
        cy.get('#tile_btn_virtual_device_div_id > h2').click()
        cy.wait(500)
        cy.log("Opens up the page with BC Services Card Login details")
        cy.contains('Virtual Card Testing')        
        cy.wait(500)
        //Type the Card serial number and passcode
        cy.get('#csn').type('SS4BPS225').should('have.value', 'SS4BPS225')
        cy.wait(500)
        cy.log("Click on Continue to go to next page")
        cy.get('#continue').click()
        cy.wait(500)
        cy.log("Enter Passcode")
        cy.get('#passcode').type('98925',{ log: false })
        cy.wait(500)
        cy.log("Click Submit")
        cy.get('#btnSubmit').click()
        cy.wait(500)
        cy.log("It should take user to validate page")
        cy.url().should('eq','https://idtest.gov.bc.ca/login/passcode/validate')
        cy.wait(500)
        cy.log("Shows a disclaimer")
        cy.contains('BC Services Card Self Services for BPS - DEV will receive the following personal identity information')
        cy.wait(500)
        cy.log("Click Submit")
        cy.get('#btnSubmit').click()
        cy.wait(500)
        //If logging in for the first Time
        cy.log("If logging in for the first time, User is asked to complete profile")
        cy.visit('https://selfservice-dev.pathfinder.gov.bc.ca/profile/')  
        cy.get('input[data-test-id="input-profile-email"]').type('SS4BPS225@gov.bc.ca').should('have.value', 'SS4BPS225@gov.bc.ca')
        cy.wait(500)
        cy.get('input[data-test-id="input-profile-phone"]').type('9819898982').should('have.value', '9819898982')
        cy.wait(500)
        cy.log("Submit profile details")
        cy.get('[data-test-id="btn-profile-update"]').click()
        cy.wait(500)
        cy.contains('Terms of Use')
        cy.contains('Indemnity')
        cy.contains('General')
        cy.get('[data-test-id="btn-submit-terms-profile"]').should('be.disabled')
        //cy.get('#scroll-target').scrollTo("bottom")
        cy.get('#scroll-target').scrollTo('0%','90%')
        cy.wait(500)
        cy.get('[data-test-id="btn-submit-terms-profile"]').should('be.enabled')
        cy.log("Test Complete")
 
    })
})