// Visit a web page
describe('Login with BC Services card in Test Server ', function()
{
    it('Should have Prod Request enabled', function(){
        cy.log("Visiting the BC Services Card [TEST] URL")
        cy.visit('https://selfservice-test.pathfinder.gov.bc.ca/')
        cy.wait(5000)
        cy.log("Click to Login")
        cy.contains('Login').click()
        cy.wait(5000)
        //For the New url
        cy.log("Should open the login page")
        cy.url().should('include','openid-connect')
        cy.log("Click on BC Services Card Login")
        //Opting for BCSC login
        cy.get('#zocial-bcsc').click()
        //cy.wait(5000)
        cy.log("Should open the BC Services Card Login Page")
        cy.url().should('eq','https://idtest.gov.bc.ca/login/entry#start')
        //cy.wait(5000)
        cy.log("Click on Virtual Card Testing")
        //Click on Virtual Card Testing
        cy.get('#tile_btn_virtual_device_div_id > h2').click()
        //cy.wait(5000)
        cy.log("Opens up the page with BC Services Card Login details")
        cy.contains('Virtual Card Testing')        
        //cy.wait(5000)
        //Type the Card serial number and passcode
        cy.get('#csn').type('SS4BPS230').should('have.value', 'SS4BPS230')
        //cy.wait(5000)
        cy.log("Click on Continue to go to next page")
        cy.get('#continue').click()
        //cy.wait(5000)
        cy.log("Enter Passcode")
        cy.get('#passcode').type('98930',{ log: false })
        //cy.wait(5000)
        cy.log("Click Submit")
        cy.get('#btnSubmit').click()
        ///cy.wait(5000)
        cy.log("It should take user to validate page")
        cy.url().should('eq','https://idtest.gov.bc.ca/login/passcode/validate')
        //cy.wait(5000)
        cy.log("Shows a disclaimer")
        cy.contains('BC Services Card Self Services for BPS - DEV will receive the following personal identity information')
        //cy.wait(5000)
        cy.log("Click Submit")
        cy.get('#btnSubmit').click()
        cy.wait(5000)
        cy.url().should('include','https://selfservice-test.pathfinder.gov.bc.ca/dashboard')
        cy.wait(1000)
        cy.get('tbody > tr >').contains('Development').click()
        cy.url().should('include','project-container')
        cy.log("The below assertion should NOT fail for TEST environment")
        cy.get('[data-test-id="btn-request-prod-access"]').should('be.enabled')
        cy.log("Test Completed")
    })
})