describe('Home Page Basic Test', function()
{
    it('Testing essential elements on home page', function()
    {
        cy.log("Visiting the BC Services Card [DEV] URL")
        cy.visit('https://selfservice-test.pathfinder.gov.bc.ca/')
        cy.wait(5000)
        cy.log("Looking for content : Beta")
        cy.contains('Beta')
        cy.wait(5000)
        cy.log("Looking for content : Login")
        cy.contains('Login')
        cy.wait(5000)
        cy.log("Looking for content : Learn More")
        cy.contains('Learn more')
        cy.wait(5000)
        cy.log("Looking for content : Get Started")
        cy.contains('Get started')
        cy.wait(5000)
        cy.log("Test Completed")

    })
})