// Visit a web page
import "cypress-keycloak-commands";
describe('BC Keycloak Login with BC services Card', function()
{
    it('Visit the BC Dev Page and Login', function(){
        cy.log("Visiting the BC Services Card [DEV] URL")
        cy.visit('https://selfservice-dev.pathfinder.gov.bc.ca/')
        cy.wait(5000)
        cy.log("Click to Login")
        cy.contains('Login').click()
        cy.wait(5000)
        //For the New url
        cy.log("Should open the login page")
        cy.url().should('include','openid-connect')
        cy.log("Click on BC Services Card Login")
        //Opting for BCSC login
        cy.get('#zocial-bcsc').click()
        cy.wait(5000)
        cy.log("Should open the BC Services Card Login Page")
        cy.url().should('eq','https://idtest.gov.bc.ca/login/entry#start')
        cy.wait(5000)
        cy.log("Click on Virtual Card Testing")
        //Click on Virtual Card Testing
        cy.get('#tile_btn_virtual_device_div_id > h2').click()
        cy.wait(5000)
        cy.log("Opens up the page with BC Services Card Login details")
        cy.contains('Virtual Card Testing')        
        cy.wait(5000)
        //Type the Card serial number and passcode
        cy.get('#csn').type('SS4BPS230').should('have.value', 'SS4BPS230')
        cy.wait(5000)
        cy.log("Click on Continue to go to next page")
        cy.get('#continue').click()
        cy.wait(5000)
        cy.log("Enter Passcode")
        cy.get('#passcode').type('98930',{ log: false })
        cy.wait(5000)
        cy.log("Click Submit")
        cy.get('#btnSubmit').click()
        cy.wait(5000)
        cy.log("It should take user to validate page")
        cy.url().should('eq','https://idtest.gov.bc.ca/login/passcode/validate')
        cy.wait(5000)
        cy.log("Shows a disclaimer")
        cy.contains('BC Services Card Self Services for BPS - DEV will receive the following personal identity information')
        cy.wait(5000)
        cy.log("Click Submit")
        cy.get('#btnSubmit').click()
        cy.wait(5000)
        //If logging in for the first Time
        cy.log("If logging in for the first time, User is asked to complete profile")
        cy.visit('https://selfservice-dev.pathfinder.gov.bc.ca/profile/')  
        cy.get('input[data-test-id="input-profile-email"]').type('SS4BPS230@gov.bc.ca').should('have.value', 'SS4BPS230@gov.bc.ca')
        cy.wait(5000)
        cy.get('input[data-test-id="input-profile-phone"]').type('9819898982').should('have.value', '9819898982')
        cy.wait(5000)
        cy.log("Submit profile details")
        cy.get('[data-test-id="btn-profile-update"]').click()
        cy.wait(5000)
        cy.log("User is taken to Dashboard")
        cy.visit('https://selfservice-dev.pathfinder.gov.bc.ca/dashboard')
        cy.wait(5000)
        cy.url().should('include','dashboard')
        //Start a new project
        cy.log("Start a new project")
        cy.wait(5000)
        cy.get('[data-test-id="btn-create-project"]').click()
        cy.log("Should direct user to the Project Info page")
        cy.visit('https://selfservice-dev.pathfinder.gov.bc.ca/project/info')
        cy.wait(5000)
        //Enter Project Name, Organization and Description
        cy.log("Enter Project Details and Submit")
        cy.get('input[data-test-id="input-org-name"]').type('BCGov').should('have.value', 'BCGov')
        cy.wait(5000)
        cy.get('input[data-test-id="input-project-name"]').type('Sample Project').should('have.value', 'Sample Project')
        cy.wait(5000)
        cy.get('textarea[data-test-id="text-project-description"]').type('Sample Description of the project').should('have.value', 'Sample Description of the project')
        cy.wait(5000)
        cy.get('[data-test-id="btn-submit-project-info"]').click()
        cy.log("Should take user to Team details page")
        cy.url().should('include','/team/')
        cy.wait(5000)
        //As of now We can proceed without adding Manager or Sponsor details
        cy.log("Enter Team Details or proceed with just Developer")
        cy.get('[data-test-id="btn-submit-project-team"]').click()
        cy.wait(5000)
        cy.log("User id directed to Technical Details page")
        cy.url().should('include','/technical/')
        cy.wait(5000)
        // Add The Technical requirement details
        cy.log("Enter Technical Details")
        cy.get('input[data-test-id="input-app-url"]').type('http://homepageurl.com').should('have.value', 'http://homepageurl.com')
        cy.wait(5000)
        cy.get('input[data-test-id="input-redirect-url0"]').type('https://redirecturl.com').should('have.value', 'https://redirecturl.com')
        cy.wait(5000)
        cy.get('[data-test-id="btn-submit-technical-req"]').click()
        cy.wait(5000)
        cy.log("User is directed to Package details page")
        // Default package
        cy.url().should('include','/package/')
        cy.wait(5000)
        cy.log("Proceed with default selected package")
        cy.get('[data-test-id="btn-submit-package-select"]').click()
        cy.wait(5000)
        cy.log("Proceed with default selected test account number")
        //Default Test Account
        cy.url().should('include','/test-account/')
        cy.wait(5000)
        cy.get('[data-test-id="btn-submit-test-account"]').click()
        cy.wait(5000)
        cy.log("User is directed to project container page")
        cy.url().should('include','/project-container')
        cy.log("Click on Submit")
        cy.get('[data-test-id="btn-submit-summary"]').click()
        cy.wait(5000)
        cy.log("Disclaimer pop up, Accept and Continue")
        cy.get('[data-test-id="btn-submit-project-summary"]').click()
        cy.wait(10000)
        cy.log("Project is submitted; Shows up in dashboard")
        cy.url().should('include','https://selfservice-dev.pathfinder.gov.bc.ca/project-container/')
        cy.wait(5000)
        cy.log("Test Completed")

    })
})