"""org_whitelist

Revision ID: 12dc55e0fd96
Revises: 
Create Date: 2020-01-03 15:36:09.727379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dc55e0fd96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_whitelist',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('org_name', sa.String(length=250), nullable=False),
                    sa.Column('head_of_org', sa.String(length=250), nullable=False),
                    sa.Column('domain', sa.String(length=50), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('modified', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_whitelist')
    # ### end Alembic commands ###
