"""signing-encryption-type

Revision ID: 21a4a3ff3229
Revises: 56f02ce3c0af
Create Date: 2020-03-19 14:39:43.971524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a4a3ff3229'
down_revision = '56f02ce3c0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technical_req', sa.Column('signing_encryption_type', sa.Integer(), nullable=True))

    op.execute("""UPDATE technical_req SET signing_encryption_type=3""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_req', 'signing_encryption_type')
    # ### end Alembic commands ###
