"""refno-correction

Revision ID: 3cb945520c97
Revises: 9e95b2c825af
Create Date: 2020-02-24 13:05:43.423588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb945520c97'
down_revision = '9e95b2c825af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('ref_no', sa.String(length=20), nullable=True))
    op.drop_column('project_users_association', 'ref_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users_association', sa.Column('ref_no', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('project', 'ref_no')
    # ### end Alembic commands ###
