"""is-prod-flag

Revision ID: 4eec959c6e5e
Revises: 81bab187cd23
Create Date: 2020-04-15 16:16:45.290159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eec959c6e5e'
down_revision = '81bab187cd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oidc_config', sa.Column('is_prod', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('technical_req', sa.Column('is_prod', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_req', 'is_prod')
    op.drop_column('oidc_config', 'is_prod')
    # ### end Alembic commands ###
