"""scope-package-changes

Revision ID: 599938806180
Revises: 84faccdd32cf
Create Date: 2020-02-18 10:46:51.190953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599938806180'
down_revision = '84faccdd32cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scope_package', sa.Column('package_code', sa.String(length=10), nullable=True))

    op.execute("""UPDATE scope_package SET package_code='p1', description='Best fit for organizations looking for identity verification only' WHERE package_name='Package 1'""")
    op.execute("""UPDATE scope_package SET package_code='p2', description='Best fit for organizations who want to communicate with users via email' WHERE package_name='Package 2'""")
    op.execute("""UPDATE scope_package SET package_code='p3', description='Best fit for organizations who want to communicate with users via physical mail' WHERE package_name='Package 3'""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scope_package', 'package_code')
    # ### end Alembic commands ###
