"""oidc-config-and-test-account

Revision ID: 84faccdd32cf
Revises: 80942474cbb5
Create Date: 2020-02-13 15:26:38.868192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84faccdd32cf'
down_revision = 'f3f863aa6896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('client_id', sa.String(length=100), nullable=True),
                    sa.Column('client_secret', sa.String(length=100), nullable=True),
                    sa.Column('registration_access_token', sa.String(length=100), nullable=True),
                    sa.Column('registration_client_uri', sa.String(length=500), nullable=True),
                    sa.Column('client_id_issued_at', sa.String(length=100), nullable=True),
                    sa.Column('client_secret_expires_at', sa.Integer(), nullable=True),
                    sa.Column('token_endpoint_auth_method', sa.String(length=100), nullable=True),
                    sa.Column('application_type', sa.String(length=100), nullable=True),
                    sa.Column('subject_type', sa.String(length=100), nullable=True),
                    sa.Column('sector_identifier_uri', sa.String(length=500), nullable=True),
                    sa.Column('id_token_encrypted_response_alg', sa.String(length=100), nullable=True),
                    sa.Column('id_token_encrypted_response_enc', sa.String(length=100), nullable=True),
                    sa.Column('userinfo_encrypted_response_alg', sa.String(length=100), nullable=True),
                    sa.Column('userinfo_encrypted_response_enc', sa.String(length=100), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('test_account',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('card_number', sa.String(length=50), nullable=False),
                    sa.Column('passcode', sa.String(length=20), nullable=False),
                    sa.Column('attributes', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oidc_config')
    op.drop_table('test_account')
    # ### end Alembic commands ###
