"""ref-no

Revision ID: 9e95b2c825af
Revises: 599938806180
Create Date: 2020-02-24 10:38:03.849481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e95b2c825af'
down_revision = '599938806180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users_association', sa.Column('ref_no', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_users_association', 'ref_no')
    # ### end Alembic commands ###
