"""audit-change

Revision ID: bb14b70909c8
Revises: d50be5c21c29
Create Date: 2020-05-01 11:17:14.045483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb14b70909c8'
down_revision = 'd50be5c21c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit', 'audit_type')
    op.add_column('audit', sa.Column('audit_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
