"""oidc-config-change

Revision ID: d10841f2ef80
Revises: 3cb945520c97
Create Date: 2020-02-27 11:50:01.140148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = 'd10841f2ef80'
down_revision = '3cb945520c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oidc_config', 'id_token_encrypted_response_enc')
    op.drop_column('oidc_config', 'userinfo_encrypted_response_alg')
    op.drop_column('oidc_config', 'sector_identifier_uri')
    op.drop_column('oidc_config', 'id_token_encrypted_response_alg')
    op.drop_column('oidc_config', 'userinfo_encrypted_response_enc')

    op.alter_column('oidc_config', 'registration_access_token', type_=sa.VARCHAR(length=5000))

    test_account = table('test_account',
                         column('card_number', sa.String),
                         column('passcode', sa.String),
                         column('attributes', sa.JSON))

    op.bulk_insert(
        test_account,
        [
            {'card_number': 'SS4BPS201', 'passcode': '98901', 'attributes': {'surname': 'ONE', 'givenname': 'SS4BPS Felecia', 'gender': 'F', 'address1': '4732 Easy Street', 'address2': 'Highlands BC V9B 3V9', 'postcode': 'V9B 3V9', 'dob': '1998-04-30'}},
            {'card_number': 'SS4BPS202', 'passcode': '98902', 'attributes': {'surname': 'TWO', 'givenname': 'SS4BPS Benjamin ', 'gender': 'M', 'address1': '308-2464 Crimson Vale', 'address2': 'Penticton BC V2A 5N1', 'postcode': 'V2A 5N1', 'dob': '2000-11-18'}},
            {'card_number': 'SS4BPS203', 'passcode': '98903', 'attributes': {'surname': 'THREE', 'givenname': 'SS4BPS Tyisha', 'gender': 'F', 'address1': '3853 Lazy Road', 'address2': 'Alexis Creek BC V0L 3I3', 'postcode': 'V0L 3I3', 'dob': '1999-03-19'}},
            {'card_number': 'SS4BPS204', 'passcode': '98904', 'attributes': {'surname': 'FOUR', 'givenname': 'SS4BPS Leah', 'gender': 'F', 'address1': '217-8030 Turning Wharf', 'address2': 'Kimberley BC V1A 3W9', 'postcode': 'V1A 3W9', 'dob': '1998-03-24'}},
            {'card_number': 'SS4BPS205', 'passcode': '98905', 'attributes': {'surname': 'FIVE', 'givenname': 'SS4BPS Dusan', 'gender': 'M', 'address1': '918-1625 Hazy Hill', 'address2': 'Fort Nelson BC V0C 4V7', 'postcode': 'V0C 4V7', 'dob': '1998-04-30'}},
            {'card_number': 'SS4BPS206', 'passcode': '98906', 'attributes': {'surname': 'SIX', 'givenname': 'SS4BPS Aubrey', 'gender': 'M', 'address1': '4388 Emerald Road', 'address2': 'Oak Bay BC V8R 7B7', 'postcode': 'V8R 7B7', 'dob': '1999-03-18'}},
            {'card_number': 'SS4BPS207', 'passcode': '98907', 'attributes': {'surname': 'SEVEN', 'givenname': 'SS4BPS Milos', 'gender': 'F', 'address1': '9761 Quaking Way', 'address2': 'Coquitlam BC V3J 8A7', 'postcode': 'V3J 8A7', 'dob': '1999-04-26'}},
            {'card_number': 'SS4BPS208', 'passcode': '98908', 'attributes': {'surname': 'EIGHT', 'givenname': 'SS4BPS Rachel', 'gender': 'M', 'address1': '106-8130 Middle Avenue', 'address2': 'Williams Lake BC V2G 6P6', 'postcode': 'V2G 6P6', 'dob': '1999-10-29'}},
            {'card_number': 'SS4BPS209', 'passcode': '98909', 'attributes': {'surname': 'NINE', 'givenname': 'SS4BPS Reiko', 'gender': 'F', 'address1': '7710 Burning Way', 'address2': 'Whistler BC V0N 2S1', 'postcode': 'V0N 2S1', 'dob': '2000-08-21'}},
            {'card_number': 'SS4BPS210', 'passcode': '98910', 'attributes': {'surname': 'TEN', 'givenname': 'SS4BPS Thanos', 'gender': 'F', 'address1': '703-6247 Bright Street', 'address2': 'Kitimat BC V8C 8T6', 'postcode': 'V8C 8T6', 'dob': '1998-10-20'}},
            {'card_number': 'SS4BPS211', 'passcode': '98911', 'attributes': {'surname': 'ELEVEN', 'givenname': 'SS4BPS Huong', 'gender': 'M', 'address1': '9664 Sweet Mews', 'address2': 'Duncan BC V9L 9U6', 'postcode': 'V9L 9U6', 'dob': '2000-01-06'}},
            {'card_number': 'SS4BPS212', 'passcode': '98912', 'attributes': {'surname': 'TWELVE', 'givenname': 'SS4BPS Dena', 'gender': 'F', 'address1': '320-6550 Sunny Square', 'address2': 'Whistler BC V0N 8M4', 'postcode': 'V0N 8M4', 'dob': '1999-07-23'}},
            {'card_number': 'SS4BPS213', 'passcode': '98913', 'attributes': {'surname': 'THIRTEEN', 'givenname': 'SS4BPS Tyisha', 'gender': 'F', 'address1': '9798 Bent Hill', 'address2': 'Esquimalt BC V9A 3E5', 'postcode': 'V9A 3E5', 'dob': '2000-05-15'}},
            {'card_number': 'SS4BPS214', 'passcode': '98914', 'attributes': {'surname': 'FOURTEEN', 'givenname': 'SS4BPS Hubert', 'gender': 'M', 'address1': '816-4297 Small Place', 'address2': 'Cranbrook BC V1C 7P7', 'postcode': 'V1C 7P7', 'dob': '1998-10-04'}},
            {'card_number': 'SS4BPS215', 'passcode': '98915', 'attributes': {'surname': 'FIFTEEN', 'givenname': 'SS4BPS Lisa', 'gender': 'F', 'address1': '9037 Shady Gardens', 'address2': 'Qualicum Beach BC V9K 5W4', 'postcode': 'V9K 5W4', 'dob': '1998-03-28'}},
            {'card_number': 'SS4BPS216', 'passcode': '98916', 'attributes': {'surname': 'SIXTEEN', 'givenname': 'SS4BPS Octavio', 'gender': 'M', 'address1': '911-5046 Harvest Wharf', 'address2': 'Campbell River BC V9W 5F3', 'postcode': 'V9W 5F3', 'dob': '1999-01-14'}},
            {'card_number': 'SS4BPS217', 'passcode': '98917', 'attributes': {'surname': 'SEVENTEEN', 'givenname': 'SS4BPS Rachel', 'gender': 'M', 'address1': '815-8999 Velvet Way', 'address2': 'Highlands BC V9B 3X7', 'postcode': 'V9B 3X7', 'dob': '1998-12-11'}},
            {'card_number': 'SS4BPS218', 'passcode': '98918', 'attributes': {'surname': 'EIGHTEEN', 'givenname': 'SS4BPS Harriett', 'gender': 'F', 'address1': '5589 Lone Circus', 'address2': 'White Rock BC V4B 7U2', 'postcode': 'V4B 7U2', 'dob': '2000-05-07'}},
            {'card_number': 'SS4BPS219', 'passcode': '98919', 'attributes': {'surname': 'NINETEEN', 'givenname': 'SS4BPS Huong', 'gender': 'M', 'address1': '608-3132 Small Close', 'address2': 'Victoria BC V8T 5C3', 'postcode': 'V8T 5C3', 'dob': '2000-02-19'}},
            {'card_number': 'SS4BPS220', 'passcode': '98920', 'attributes': {'surname': 'TWENTY', 'givenname': 'SS4BPS Anuska', 'gender': 'F', 'address1': '2715 Emerald Lane', 'address2': 'Hope BC V0X 1S1', 'postcode': 'V0X 1S1', 'dob': '1999-12-04'}},
            {'card_number': 'SS4BPS221', 'passcode': '98921', 'attributes': {'surname': 'TWENTYONE', 'givenname': 'SS4BPS Mao', 'gender': 'F', 'address1': '3685 Burning Grove', 'address2': 'Maple Ridge BC V2W 9H8', 'postcode': 'V2W 9H8', 'dob': '1998-01-30'}},
            {'card_number': 'SS4BPS222', 'passcode': '98922', 'attributes': {'surname': 'TWENTYTWO', 'givenname': 'SS4BPS Myrle', 'gender': 'F', 'address1': '8792 Noble Wharf', 'address2': 'Sooke BC V0S 5U5', 'postcode': 'V0S 5U5', 'dob': '2000-04-14'}},
            {'card_number': 'SS4BPS223', 'passcode': '98923', 'attributes': {'surname': 'TWENTYTHREE', 'givenname': 'SS4BPS Ayisha', 'gender': 'F', 'address1': '719-3911 Round Street', 'address2': 'Ladysmith BC V9G 5Y3', 'postcode': 'V9G 5Y3', 'dob': '1999-12-30'}},
            {'card_number': 'SS4BPS224', 'passcode': '98924', 'attributes': {'surname': 'TWENTYFOUR', 'givenname': 'SS4BPS Lin', 'gender': 'F', 'address1': '7917 Round Lane', 'address2': 'Terrace BC V8G 6B2', 'postcode': 'V8G 6B2', 'dob': '1999-02-04'}},
            {'card_number': 'SS4BPS225', 'passcode': '98925', 'attributes': {'surname': 'TWENTYFIVE', 'givenname': 'SS4BPS Eugena', 'gender': 'F', 'address1': '3282 Pied Row', 'address2': 'Ladysmith BC V9G 6D4', 'postcode': 'V9G 6D4', 'dob': '1998-10-03'}},
            {'card_number': 'SS4BPS226', 'passcode': '98926', 'attributes': {'surname': 'TWENTYSIX', 'givenname': 'SS4BPS Nita', 'gender': 'F', 'address1': '803-7361 Dusty Road', 'address2': 'Fernie BC V0B 9D4', 'postcode': 'V0B 9D4', 'dob': '1998-12-28'}},
            {'card_number': 'SS4BPS227', 'passcode': '98927', 'attributes': {'surname': 'TWENTYSEVEN', 'givenname': 'SS4BPS Lin', 'gender': 'F', 'address1': '401-2693 Dewy Drive', 'address2': 'Gold River BC V0P 5Z7', 'postcode': 'V0P 5Z7', 'dob': '2000-10-05'}},
            {'card_number': 'SS4BPS228', 'passcode': '98928', 'attributes': {'surname': 'TWENTYEIGHT', 'givenname': 'SS4BPS Chun', 'gender': 'F', 'address1': '2204 Lonely Grove', 'address2': 'Fort Nelson BC V0C 5O6', 'postcode': 'V0C 5O6', 'dob': '2000-06-19'}},
            {'card_number': 'SS4BPS229', 'passcode': '98929', 'attributes': {'surname': 'TWENTYNINE', 'givenname': 'SS4BPS Reiko', 'gender': 'F', 'address1': '7725 Cinder Mews', 'address2': 'Mission West BC V4S 1V2', 'postcode': 'V4S 1V2', 'dob': '1998-03-14'}},
            {'card_number': 'SS4BPS230', 'passcode': '98930', 'attributes': {'surname': 'THIRTY', 'givenname': 'SS4BPS Nguyen', 'gender': 'M', 'address1': '9601 Harrison Street', 'address2': 'Dawson Creek BC V1G 1N2', 'postcode': 'V1G 1N2', 'dob': '2000-04-14'}},
            {'card_number': 'SS4BPS231', 'passcode': '98931', 'attributes': {'surname': 'THIRTYONE', 'givenname': 'SS4BPS Thanos', 'gender': 'F', 'address1': '501-6489 Clear Close', 'address2': 'Burnaby BC V3N 7Z2', 'postcode': 'V3N 7Z2', 'dob': '1999-08-06'}},
            {'card_number': 'SS4BPS232', 'passcode': '98932', 'attributes': {'surname': 'THIRTYTWO', 'givenname': 'SS4BPS Idella', 'gender': 'F', 'address1': '9424 Hazy Vale', 'address2': 'Saltspring Island BC V8K 2T2', 'postcode': 'V8K 2T2', 'dob': '2000-04-29'}},
            {'card_number': 'SS4BPS233', 'passcode': '98933', 'attributes': {'surname': 'THIRTYTHREE', 'givenname': 'SS4BPS William', 'gender': 'M', 'address1': '7939 Noble Street', 'address2': 'Dawson Creek BC V1G 2T5', 'postcode': 'V1G 2T5', 'dob': '1998-07-29'}},
            {'card_number': 'SS4BPS234', 'passcode': '98934', 'attributes': {'surname': 'THIRTYFOUR', 'givenname': 'SS4BPS Moses', 'gender': 'M', 'address1': '5649 Dewy Grove', 'address2': 'Delta BC V4C 5R9', 'postcode': 'V4C 5R9', 'dob': '1999-10-29'}},
            {'card_number': 'SS4BPS235', 'passcode': '98935', 'attributes': {'surname': 'THIRTYFIVE', 'givenname': 'SS4BPS Chapa', 'gender': 'M', 'address1': '206-3134 Gentle Mews', 'address2': 'Winfield BC V4V 4G9', 'postcode': 'V4V 4G9', 'dob': '1998-12-28'}},
            {'card_number': 'SS4BPS236', 'passcode': '98936', 'attributes': {'surname': 'THIRTYSIX', 'givenname': 'SS4BPS Kerrie', 'gender': 'F', 'address1': '416-3241 Lost Crescent', 'address2': 'Terrace BC V8G 1P2', 'postcode': 'V8G 1P2', 'dob': '2000-04-19'}},
            {'card_number': 'SS4BPS237', 'passcode': '98937', 'attributes': {'surname': 'THIRTYSEVEN', 'givenname': 'SS4BPS Ulla', 'gender': 'M', 'address1': '713-9307 Bent Crescent', 'address2': 'Sidney BC V8L 1C6', 'postcode': 'V8L 1C6', 'dob': '2000-09-22'}},
            {'card_number': 'SS4BPS238', 'passcode': '98938', 'attributes': {'surname': 'THIRTYEIGHT', 'givenname': 'SS4BPS Tenisha', 'gender': 'F', 'address1': '4874 Square Circus', 'address2': 'Quesnel BC V2J 6J8', 'postcode': 'V2J 6J8', 'dob': '1999-04-16'}},
            {'card_number': 'SS4BPS239', 'passcode': '98939', 'attributes': {'surname': 'THIRTYNINE', 'givenname': 'SS4BPS Dusan', 'gender': 'M', 'address1': '212-3051 Easy Drive', 'address2': 'Westbank BC V4T 9M4', 'postcode': 'V4T 9M4', 'dob': '2000-07-26'}},
            {'card_number': 'SS4BPS240', 'passcode': '98940', 'attributes': {'surname': 'FORTY', 'givenname': 'SS4BPS Ayana', 'gender': 'F', 'address1': '9731 Pretty Gardens', 'address2': 'Saanich West BC V9E 1L5', 'postcode': 'V9E 1L5', 'dob': '1999-04-28'}},
            {'card_number': 'SS4BPS241', 'passcode': '98941', 'attributes': {'surname': 'FORTYONE', 'givenname': 'SS4BPS Dominick', 'gender': 'M', 'address1': '4580 Orange Hill', 'address2': 'Burnaby BC V3N 9J1', 'postcode': 'V3N 9J1', 'dob': '2000-01-20'}},
            {'card_number': 'SS4BPS242', 'passcode': '98942', 'attributes': {'surname': 'FORTYTWO', 'givenname': 'SS4BPS Idella', 'gender': 'F', 'address1': '712-4919 Hazy Street', 'address2': 'Prince Rupert BC V8J 8D6', 'postcode': 'V8J 8D6', 'dob': '1999-08-26'}},
            {'card_number': 'SS4BPS243', 'passcode': '98943', 'attributes': {'surname': 'FORTYTHREE', 'givenname': 'SS4BPS Danny', 'gender': 'M', 'address1': '7247 Cinder Vale', 'address2': 'Courtenay BC V9J 5V2', 'postcode': 'V9J 5V2', 'dob': '1999-12-18'}},
            {'card_number': 'SS4BPS244', 'passcode': '98944', 'attributes': {'surname': 'FORTYFOUR', 'givenname': 'SS4BPS Chun', 'gender': 'F', 'address1': '905-9406 Misty Close', 'address2': 'Port Alberni BC V9Y 7C4', 'postcode': 'V9Y 7C4', 'dob': '2000-06-21'}},
            {'card_number': 'SS4BPS245', 'passcode': '98945', 'attributes': {'surname': 'FORTYFIVE', 'givenname': 'SS4BPS William', 'gender': 'M', 'address1': '9979 Big Mews', 'address2': 'Cedar BC V9X 9L8', 'postcode': 'V9X 9L8', 'dob': '1999-04-07'}},
            {'card_number': 'SS4BPS246', 'passcode': '98946', 'attributes': {'surname': 'FORTYSIX', 'givenname': 'SS4BPS Sebastian', 'gender': 'M', 'address1': '4566 Harvest Way', 'address2': 'Quesnel BC V2J 7A9', 'postcode': 'V2J 7A9', 'dob': '2000-07-04'}},
            {'card_number': 'SS4BPS247', 'passcode': '98947', 'attributes': {'surname': 'FORTYSEVEN', 'givenname': 'SS4BPS Bena', 'gender': 'F', 'address1': '904-4319 Jagged Avenue', 'address2': 'Chemainus BC V0R 2V4', 'postcode': 'V0R 2V4', 'dob': '2000-04-29'}},
            {'card_number': 'SS4BPS248', 'passcode': '98948', 'attributes': {'surname': 'FORTYEIGHT', 'givenname': 'SS4BPS Ayisha', 'gender': 'F', 'address1': '212-5314 Middle Vale', 'address2': 'Mission West BC V4S 3Q3', 'postcode': 'V4S 3Q3', 'dob': '1999-07-20'}},
            {'card_number': 'SS4BPS249', 'passcode': '98949', 'attributes': {'surname': 'FORTYNINE', 'givenname': 'SS4BPS Hubert', 'gender': 'M', 'address1': '7881 Tawny Vale', 'address2': 'Fernie BC V0B 6K3', 'postcode': 'V0B 6K3', 'dob': '1998-04-18'}},
            {'card_number': 'SS4BPS250', 'passcode': '98950', 'attributes': {'surname': 'FIFTY', 'givenname': 'SS4BPS Glenn', 'gender': 'M', 'address1': '219-1227 Misty Drive', 'address2': 'Chemainus BC V0R 2H4', 'postcode': 'V0R 2H4', 'dob': '1999-11-05'}}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oidc_config', sa.Column('userinfo_encrypted_response_enc', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('oidc_config', sa.Column('id_token_encrypted_response_alg', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('oidc_config', sa.Column('sector_identifier_uri', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('oidc_config', sa.Column('userinfo_encrypted_response_alg', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('oidc_config', sa.Column('id_token_encrypted_response_enc', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
