"""audit

Revision ID: d50be5c21c29
Revises: fbbae69086d6
Create Date: 2020-04-28 14:31:32.800242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50be5c21c29'
down_revision = 'fbbae69086d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_type', sa.Integer(), nullable=False),
    sa.Column('audit_type_id', sa.String(), nullable=True),
    sa.Column('sub_type', sa.String(), nullable=True),
    sa.Column('sub_type_id', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('logged_in', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history')
    op.drop_table('audit')
    # ### end Alembic commands ###
