"""package-to-scope

Revision ID: e9d01a8a0b58
Revises: d10841f2ef80
Create Date: 2020-03-02 09:50:40.610772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9d01a8a0b58'
down_revision = 'd10841f2ef80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""UPDATE scope_package SET claim_names='["openid","profile"]' WHERE package_code='p1'""")
    op.execute("""UPDATE scope_package SET claim_names='["openid","profile","email"]' WHERE package_code='p2'""")
    op.execute("""UPDATE scope_package SET claim_names='["openid","profile","address"]' WHERE package_code='p3'""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
