"""package-desc-change

Revision ID: f18e00b6fc2d
Revises: f7f05ebec1f8
Create Date: 2020-05-28 17:06:29.546365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18e00b6fc2d'
down_revision = 'f7f05ebec1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""UPDATE scope_package SET description='Best fit for organizations that need physical address attributes' WHERE package_code='p3'""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
