"""user-terms

Revision ID: f7f05ebec1f8
Revises: bb14b70909c8
Create Date: 2020-05-06 13:57:34.812734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f05ebec1f8'
down_revision = 'bb14b70909c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('terms_accepted', sa.Boolean(), nullable=False, server_default='1'))
    op.alter_column('audit', 'new_value', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'terms_accepted')
    # ### end Alembic commands ###
