"""encryption-encoding-and-product-delete

Revision ID: fbbae69086d6
Revises: 4eec959c6e5e
Create Date: 2020-04-22 14:56:19.935304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbae69086d6'
down_revision = '4eec959c6e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('technical_req', sa.Column('id_token_encrypted_response_enc', sa.String(length=20), nullable=True))
    op.add_column('technical_req', sa.Column('userinfo_encrypted_response_enc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_req', 'userinfo_encrypted_response_enc')
    op.drop_column('technical_req', 'id_token_encrypted_response_enc')
    op.drop_column('project', 'is_deleted')
    # ### end Alembic commands ###
